api/urls.py
from django.urls import path, include
from api.models import CourseResource, CategoryResource
from tastypie.api import Api

api = Api(api_name='v1')

course_resource = CourseResource()
category_resource = CategoryResource()
api.register(course_resource)
api.register(category_resource)

urlpatterns = [
    path('', include(api.urls),name='index')

]

base/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include('api.urls'))
    #path('api/', include(category_resource.urls)),

]

# api/v1/courses

# api/v1/categories

shop/urls.py
from django.urls import path
from . import views

app_name= 'shop'
urlpatterns = [

    path('', views.index, name = 'index' ),
    path('<int:course_id>', views.single_course, name='single_course'),
]

api/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication



class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get', 'post', 'delete','patch']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete','patch']
        excludes = ['reviews_qty', 'created_at']
        authentication = CustomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category

        return bundle

    def dehydrate_title(self, bundle):
        return bundle.data['title'].upper()


# /api/v1/categories
# /api/v1/courses

shop/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=300)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class Course(models.Model):
    title = models.CharField(max_length=255)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title + ' ' + str(self.students_qty)

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses':courses})

def single_course(request, course_id):
    #option oun
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'shop/single_course.html', {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404()

    #option two
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <div class="container">
        <a href={% url "shop:index" %} class="navbar-brand">Центр обслуживания парапланов</a>
        <span class="navbar-text">
           <a href="/admin/" class="me-2" target="_blank">ADMIN</a>
            <a href="/api/v1/" target="_blank">API</a>

        </span>
    </div>
</nav>
<main class="container">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/shop/courses.html
{% extends 'base.html' %}
<title>{% block title %}Парапланерный сервис {% endblock %}</title>
{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
	<thead class="table-dark">
		<tr>
			<td>Title</td>
			<td>Category</td>
			<td>Price</td>
			<td>students</td>
			<td></td>
		</tr>
    </thead>
    <tbody>
		<tr>
			{%for course in courses%}

			<!--<td><a href="{{course.id}}">{{course.title}}</a></td>-->
			<td><a href={% url "shop:single_course" course.id %}>{{course.title}}</a></td>
			<td>{{course.category}}</td>
			<td>{{course.price}}</td>
			<td>{{course.students_qty}}</td>
			<td><button class="btn btn-primary">Жми</button></td>
		</tr>
	{%endfor%}
	</tbody>
</table>
{% endblock %}

templates/shop/single_course.html
{% extends 'base.html' %}
{% block title %} {{ course.title }}{% endblock %}

{% block content %}
<h1 class="mt-5"> {{ course.title }} </h1>
<h2> {{ course.category }}</h2>
<p> price:{{ course.price }} </p>
<p> Students_qty:{{ course.students.qty }} </p>
<button class="btn btn-primary">Жми</button>
{% endblock %}